#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
#if defined(__cplusplus)
extern "C" {
#endif

extern void _CaDynamics_E2_reg(void);
extern void _Ca_HVA_reg(void);
extern void _Ca_LVAst_reg(void);
extern void _HCN1_reg(void);
extern void _IC_reg(void);
extern void _IKsin_reg(void);
extern void _Ih_reg(void);
extern void _Im_reg(void);
extern void _K_Pst_reg(void);
extern void _K_Tst_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _Nca_reg(void);
extern void _ProbAMPANMDA_EMS_reg(void);
extern void _ProbGABAAB_EMS_reg(void);
extern void _SK_E2_reg(void);
extern void _SKv3_1_reg(void);
extern void _ar_traub_reg(void);
extern void _branching_reg(void);
extern void _cadad_reg(void);
extern void _cadyn_reg(void);
extern void _cagk_reg(void);
extern void _cal_mh_reg(void);
extern void _cal_mig_reg(void);
extern void _can_mig_reg(void);
extern void _cancr_reg(void);
extern void _canin_reg(void);
extern void _cat_mig_reg(void);
extern void _cat_traub_reg(void);
extern void _catcb_reg(void);
extern void _ch_CavL_reg(void);
extern void _ch_CavN_reg(void);
extern void _ch_KCaS_reg(void);
extern void _ch_Kdrfastngf_reg(void);
extern void _ch_KvAngf_reg(void);
extern void _ch_KvCaB_reg(void);
extern void _ch_Navngf_reg(void);
extern void _ch_leak_reg(void);
extern void _dipole_reg(void);
extern void _dipole_pp_reg(void);
extern void _gabab_reg(void);
extern void _h_BS_reg(void);
extern void _h_harnett_reg(void);
extern void _h_kole_reg(void);
extern void _h_migliore_reg(void);
extern void _hin_reg(void);
extern void _ican_sidi_reg(void);
extern void _iccr_reg(void);
extern void _iconc_Ca_reg(void);
extern void _ikscr_reg(void);
extern void _kBK_reg(void);
extern void _kap_BS_reg(void);
extern void _kapcb_reg(void);
extern void _kapin_reg(void);
extern void _kca_reg(void);
extern void _kctin_reg(void);
extern void _kdmc_BS_reg(void);
extern void _kdr_BS_reg(void);
extern void _kdrcr_reg(void);
extern void _kdrin_reg(void);
extern void _km_reg(void);
extern void _kv_reg(void);
extern void _my_exp2syn_reg(void);
extern void _na12_reg(void);
extern void _na12_mut_reg(void);
extern void _na16_reg(void);
extern void _na16_mut_reg(void);
extern void _nafcr_reg(void);
extern void _nafx_reg(void);
extern void _nap_sidi_reg(void);
extern void _nax_BS_reg(void);
extern void _naz_reg(void);
extern void _savedist_reg(void);
extern void _vclmp_pl_reg(void);
extern void _vecstim_reg(void);

void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"sim/mod/CaDynamics_E2.mod\"");
    fprintf(stderr, " \"sim/mod/Ca_HVA.mod\"");
    fprintf(stderr, " \"sim/mod/Ca_LVAst.mod\"");
    fprintf(stderr, " \"sim/mod/HCN1.mod\"");
    fprintf(stderr, " \"sim/mod/IC.mod\"");
    fprintf(stderr, " \"sim/mod/IKsin.mod\"");
    fprintf(stderr, " \"sim/mod/Ih.mod\"");
    fprintf(stderr, " \"sim/mod/Im.mod\"");
    fprintf(stderr, " \"sim/mod/K_Pst.mod\"");
    fprintf(stderr, " \"sim/mod/K_Tst.mod\"");
    fprintf(stderr, " \"sim/mod/MyExp2SynBB.mod\"");
    fprintf(stderr, " \"sim/mod/MyExp2SynNMDABB.mod\"");
    fprintf(stderr, " \"sim/mod/Nca.mod\"");
    fprintf(stderr, " \"sim/mod/ProbAMPANMDA_EMS.mod\"");
    fprintf(stderr, " \"sim/mod/ProbGABAAB_EMS.mod\"");
    fprintf(stderr, " \"sim/mod/SK_E2.mod\"");
    fprintf(stderr, " \"sim/mod/SKv3_1.mod\"");
    fprintf(stderr, " \"sim/mod/ar_traub.mod\"");
    fprintf(stderr, " \"sim/mod/branching.mod\"");
    fprintf(stderr, " \"sim/mod/cadad.mod\"");
    fprintf(stderr, " \"sim/mod/cadyn.mod\"");
    fprintf(stderr, " \"sim/mod/cagk.mod\"");
    fprintf(stderr, " \"sim/mod/cal_mh.mod\"");
    fprintf(stderr, " \"sim/mod/cal_mig.mod\"");
    fprintf(stderr, " \"sim/mod/can_mig.mod\"");
    fprintf(stderr, " \"sim/mod/cancr.mod\"");
    fprintf(stderr, " \"sim/mod/canin.mod\"");
    fprintf(stderr, " \"sim/mod/cat_mig.mod\"");
    fprintf(stderr, " \"sim/mod/cat_traub.mod\"");
    fprintf(stderr, " \"sim/mod/catcb.mod\"");
    fprintf(stderr, " \"sim/mod/ch_CavL.mod\"");
    fprintf(stderr, " \"sim/mod/ch_CavN.mod\"");
    fprintf(stderr, " \"sim/mod/ch_KCaS.mod\"");
    fprintf(stderr, " \"sim/mod/ch_Kdrfastngf.mod\"");
    fprintf(stderr, " \"sim/mod/ch_KvAngf.mod\"");
    fprintf(stderr, " \"sim/mod/ch_KvCaB.mod\"");
    fprintf(stderr, " \"sim/mod/ch_Navngf.mod\"");
    fprintf(stderr, " \"sim/mod/ch_leak.mod\"");
    fprintf(stderr, " \"sim/mod/dipole.mod\"");
    fprintf(stderr, " \"sim/mod/dipole_pp.mod\"");
    fprintf(stderr, " \"sim/mod/gabab.mod\"");
    fprintf(stderr, " \"sim/mod/h_BS.mod\"");
    fprintf(stderr, " \"sim/mod/h_harnett.mod\"");
    fprintf(stderr, " \"sim/mod/h_kole.mod\"");
    fprintf(stderr, " \"sim/mod/h_migliore.mod\"");
    fprintf(stderr, " \"sim/mod/hin.mod\"");
    fprintf(stderr, " \"sim/mod/ican_sidi.mod\"");
    fprintf(stderr, " \"sim/mod/iccr.mod\"");
    fprintf(stderr, " \"sim/mod/iconc_Ca.mod\"");
    fprintf(stderr, " \"sim/mod/ikscr.mod\"");
    fprintf(stderr, " \"sim/mod/kBK.mod\"");
    fprintf(stderr, " \"sim/mod/kap_BS.mod\"");
    fprintf(stderr, " \"sim/mod/kapcb.mod\"");
    fprintf(stderr, " \"sim/mod/kapin.mod\"");
    fprintf(stderr, " \"sim/mod/kca.mod\"");
    fprintf(stderr, " \"sim/mod/kctin.mod\"");
    fprintf(stderr, " \"sim/mod/kdmc_BS.mod\"");
    fprintf(stderr, " \"sim/mod/kdr_BS.mod\"");
    fprintf(stderr, " \"sim/mod/kdrcr.mod\"");
    fprintf(stderr, " \"sim/mod/kdrin.mod\"");
    fprintf(stderr, " \"sim/mod/km.mod\"");
    fprintf(stderr, " \"sim/mod/kv.mod\"");
    fprintf(stderr, " \"sim/mod/my_exp2syn.mod\"");
    fprintf(stderr, " \"sim/mod/na12.mod\"");
    fprintf(stderr, " \"sim/mod/na12_mut.mod\"");
    fprintf(stderr, " \"sim/mod/na16.mod\"");
    fprintf(stderr, " \"sim/mod/na16_mut.mod\"");
    fprintf(stderr, " \"sim/mod/nafcr.mod\"");
    fprintf(stderr, " \"sim/mod/nafx.mod\"");
    fprintf(stderr, " \"sim/mod/nap_sidi.mod\"");
    fprintf(stderr, " \"sim/mod/nax_BS.mod\"");
    fprintf(stderr, " \"sim/mod/naz.mod\"");
    fprintf(stderr, " \"sim/mod/savedist.mod\"");
    fprintf(stderr, " \"sim/mod/vclmp_pl.mod\"");
    fprintf(stderr, " \"sim/mod/vecstim.mod\"");
    fprintf(stderr, "\n");
  }
  _CaDynamics_E2_reg();
  _Ca_HVA_reg();
  _Ca_LVAst_reg();
  _HCN1_reg();
  _IC_reg();
  _IKsin_reg();
  _Ih_reg();
  _Im_reg();
  _K_Pst_reg();
  _K_Tst_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _Nca_reg();
  _ProbAMPANMDA_EMS_reg();
  _ProbGABAAB_EMS_reg();
  _SK_E2_reg();
  _SKv3_1_reg();
  _ar_traub_reg();
  _branching_reg();
  _cadad_reg();
  _cadyn_reg();
  _cagk_reg();
  _cal_mh_reg();
  _cal_mig_reg();
  _can_mig_reg();
  _cancr_reg();
  _canin_reg();
  _cat_mig_reg();
  _cat_traub_reg();
  _catcb_reg();
  _ch_CavL_reg();
  _ch_CavN_reg();
  _ch_KCaS_reg();
  _ch_Kdrfastngf_reg();
  _ch_KvAngf_reg();
  _ch_KvCaB_reg();
  _ch_Navngf_reg();
  _ch_leak_reg();
  _dipole_reg();
  _dipole_pp_reg();
  _gabab_reg();
  _h_BS_reg();
  _h_harnett_reg();
  _h_kole_reg();
  _h_migliore_reg();
  _hin_reg();
  _ican_sidi_reg();
  _iccr_reg();
  _iconc_Ca_reg();
  _ikscr_reg();
  _kBK_reg();
  _kap_BS_reg();
  _kapcb_reg();
  _kapin_reg();
  _kca_reg();
  _kctin_reg();
  _kdmc_BS_reg();
  _kdr_BS_reg();
  _kdrcr_reg();
  _kdrin_reg();
  _km_reg();
  _kv_reg();
  _my_exp2syn_reg();
  _na12_reg();
  _na12_mut_reg();
  _na16_reg();
  _na16_mut_reg();
  _nafcr_reg();
  _nafx_reg();
  _nap_sidi_reg();
  _nax_BS_reg();
  _naz_reg();
  _savedist_reg();
  _vclmp_pl_reg();
  _vecstim_reg();
}

#if defined(__cplusplus)
}
#endif
